Exchanged contents of workflow files

diff --git a/.github/workflows/release-chat.yml b/.github/workflows/release-chat.yml
--- a/.github/workflows/release-chat.yml
+++ b/.github/workflows/release-chat.yml
@@ -1,36 +1,50 @@
-name: Release Docker Image
+name: Release Chat Service
 
 on:
   workflow_dispatch:
+    inputs:
+      version:
+        description: "Version to release (e.g.,v1.0.0)"
+        required: true
 
 env:
-  APP_NAME: global-chat
-  GO_VERSION: "1.25.5"
-  REGISTRY: ghcr.io
-  IMAGE_NAME: ${{ github.repository }}
+  IMAGE_NAME: ghcr.io/${{ github.repository }}/chat
 
 jobs:
   build:
-    runs-on: ubuntu-latest
+    runs-on: ununtu-latest
 
     permissions:
       contents: read
       packages: write
-      id-token: write
 
     steps:
-      - name: Checkout repository code
+      - name: Checkout repository
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
 
-      - name: Resolve version from the latest tag
-        id: version
+      - name: Validate version format
         run: |
-          VERSION=$(git describe --tags --abbrev=0)
-          echo "VERSION=$VERSION" >> $GITHUB_ENV
-          echo "Releasing version $VERSION"
-      
+          if [[ ! "${{ github.event.inputs.version }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+          echo "Invalid version format. Use vX.Y.Z"
+          exit 1
+          fi
+
+      - name: Verify tag exists
+        run: |
+          TAG="services/chat/${{ github.event.inputs.version }}"
+          git fetch --tags
+          if ! git rev-parse "$TAG" >/dev/null 2>&1; then
+            echo "Tag $TAG does not exist!"
+            exit 1
+          fi
+          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
+
+      - name: Checkout tag
+        run: |
+          git checkout services/chat/${{ github.event.inputs.version }}
+
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
       
@@ -44,11 +58,12 @@ jobs:
       - name: Build and push Docker image
         uses: docker/build-push-action@v5
         with:
-          context: .
+          context: ./services/chat
+          file: ./services/chat/Dockerfile
           push: true
           tags: |
-            ghcr.io/tauhid-uap/global-chat:${{ env.VERSION }}
-            ghcr.io/tauhid-uap/global-chat:latest
+            ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
+            ${{ env.IMAGE_NAME }}:latest
           build-args: |
             VERSION=${{ env.VERSION }}
 
@@ -60,7 +75,7 @@ jobs:
 
       - name: Upload static assets
         run: |
-          aws s3 sync static/ \
+          aws s3 sync services/chat/static/ \
            s3://${{secrets.ARTIFACT_BUCKET}}/global-chat-static/${VERSION}/ \
            --delete
 
